name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ steps.meta.outputs.tags }}:$(date +%s)
    - name: Set the value
      id: public-Ip
      run: |
        echo "curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'=public_ip" >> $GITHUB_ENV
    - name: Use the value
      id: public-ip-output
      run: |
        echo "${{ env.public_ip }}" 
